service_type: FilterJointTrajectoryWithConstraints
filter_chain:
  -
    name: unnormalize_trajectory
    type: UnNormalizeFilterJointTrajectoryWithConstraints
  -
    name: cubic_spline_short_cutter_smoother
    type: CubicSplineShortCutterFilterJointTrajectoryWithConstraints
    params: {discretization: 0.01}
  -
    name: n_point_filter
    type: IndustrialNPointFilterJointTrajectoryWithConstraints
    params: {n_points: 75}


